name: Bug Report
description: Create a bug report
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '....'
        2. Click on '....'
        3. See the error
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear description of what you expected to happen.
    validations:
      required: true
  - type: input
    id: jp-version
    attributes:
      label: CTPF Version
      description: Which commit are you using of CTPF?
      placeholder: "e.g. Pre-Alpha 1.1.0 - 2e685a431059df912443acdbf1c6000ad108ba9f"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Relevant Assets/Logs
      description: |
        A list of assets (logs, screenshots, etc) relevant to this bug.
        Tip: You can attach image(s) or logs by clicking this area to highlight it and then dragging files in.
      placeholder: |
        To upload the log, copy from crash window; Or
        - Drag and drop them into this text area.
    validations:
      required: true
